### PR TITLE
Help reworked

### PR DESCRIPTION
**Pull request by comradekingu**
Will reread

### CODE REVIEW

**Comment by hvdwolf** [comment]
Please tell me how you midify the source files. I found an error in the program_strings, but also see a typo in your just delivered original help_text

**Comment by comradekingu** [comment]
@hvdwolf Just using the GitHub editor. I'll go over the source strings a few more times.
This PR is 85% there.

**Comment by hvdwolf** [comment]
Strange. When I go over the english translation it is read-only for me, even if I am administrator.

**Comment by comradekingu** [comment]
@hvdwolf You mean the Git repo?
I can edit https://hosted.weblate.org/zen/jexiftoolgui/program_strings/en/?q= and
https://hosted.weblate.org/zen/jexiftoolgui/help-texts/en/?q=
directly. I am the same type of user as you there.

I checked "Allow edits by maintainers" for my PRs to see if that makes any difference.

**Comment by hvdwolf** [comment]
I didn't know the "zen" link. That works for me as well.

**Pull request merged**
